version: '3.8'

services:
  backend:
    build:
      context: ./snake-game/backend
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./snake-game/client
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
