name: Destroy Infrastructure

on:
  push:
    branches:
      - test
  
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_DIR: terraform

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform destroy -auto-approve
